OC\PlatformBundle\Entity\AdvertSkill:
    type: entity
    table: null
    repositoryClass: OC\PlatformBundle\Repository\AdvertSkillRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        level:
            type: string
            length: 255
    lifecycleCallbacks: {  }
