OC\PlatformBundle\Entity\Application:
    type: entity
    table: null
    repositoryClass: OC\PlatformBundle\Repository\ApplicationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: 255
        content:
            type: string
            length: 255
        date:
            type: datetimetz
    lifecycleCallbacks: {  }
